alias gate-config='/usr/local/bin/gate-config.sh'
alias gate-menu='/usr/local/bin/gate-menu.sh'
alias gate-status='/usr/local/bin/gate-status.sh'
alias gate-watchdog='/usr/local/bin/gate-watchdog.sh'
alias gate-logs='journalctl -u owen-gateway -f'
alias gate-restart='systemctl restart owen-gateway'
alias gate-service='systemctl status owen-gateway --no-pager -l'
